Repository anuj123upadhyay/MegaBlog, pull requests merged in 2024-10, with the labels that each got.

#13 added shacn and improved home page
  components.json
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/componenets/Footer/Footer.jsx
  src/componenets/Logo.jsx
  src/components/AuthLayout.jsx
  src/components/Button.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Header/LogoutBtn.jsx
  src/components/Input.jsx
  src/components/Login.jsx
  src/components/Logo.jsx
  src/components/PostCard.jsx
  src/components/RTE.jsx
  src/components/Select.jsx
  src/components/Signup.jsx
  src/components/container/Container.jsx
  src/components/index.js
  src/components/postForm/PostForm.jsx
  src/components/ui/badge.tsx
  src/index.css
  src/lib/utils.ts
  src/main.jsx
  src/pages/AddPost.jsx
  src/pages/AllPost.jsx
  src/pages/EditPost.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Post.jsx
  src/pages/Signup.jsx
  tailwind.config.js
  tsconfig.json
  vite.config.js
Labels: gssoc-ext, hacktoberfest-accepted

#40 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, hacktoberfest-accepted, gssoc ext

#29 hero section
  .eslintrc.cjs
  components.json
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/componenets/Footer/Footer.jsx
  src/componenets/Header/Header.jsx
  src/componenets/Hero/Hero.jsx
  src/componenets/Logo.jsx
  src/componenets/container/Container.jsx
  src/components/ui/badge.tsx
  src/index.css
  src/lib/utils.ts
  src/pages/Home.jsx
  tailwind.config.js
  tsconfig.json
Labels: enhancement, gssoc-ext, level2

#68 Feat/scroll to top
  src/App.jsx
  src/components/ui/BackToTopButton.tsx
  tailwind.config.js
Labels: enhancement, gssoc-ext, level2

#76 Added privacy policy page
  src/componenets/Footer/Footer.jsx
  src/componenets/PrivacyPolicy.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level2

#69 Toggle text color
  package-lock.json
  src/App.css
  src/App.jsx
  src/componenets/Footer/Footer.jsx
  src/componenets/Header/Header.jsx
  src/componenets/Hero/Hero.jsx
  src/pages/AffiliateProgram.jsx
Labels: enhancement, gssoc-ext, level2

#75 Added contact form with submission of data #64
  src/App.css
  src/assets/contactPageBg.jpg
  src/componenets/ContactPage.jsx
  src/componenets/Footer/Footer.jsx
  src/componenets/Header/Header.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level3

#87 Added customer support page
  src/componenets/Footer/Footer.jsx
  src/componenets/SupportPage.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level2

#89 fixed the navabr
  src/componenets/Header/Header.jsx
Labels: bug, enhancement, gssoc-ext, level2

#94 Add post page responsive
  src/componenets/Header/Header.jsx
  src/componenets/postForm/PostForm.jsx
Labels: gssoc-ext, level3

#109 Customer support Page changed
  src/componenets/SupportPage.jsx
Labels: enhancement, gssoc-ext, level3

#107 Added faq to home page
  src/componenets/Footer/Footer.jsx
  src/main.jsx
  src/pages/FAQ.jsx
  src/pages/Home.jsx
Labels: enhancement, gssoc-ext, level3

#104 changed Favicon
  index.html
  src/assets/favicon.png
Labels: gssoc-ext, level2

#117 Fixed footer alignment & make responsive
  src/componenets/Footer/Footer.jsx
Labels: gssoc-ext, level2

#114 Navbar becomes sticky after scrolling the first 10vh of the webpage
  package-lock.json
  src/componenets/Header/Header.jsx
Labels: gssoc-ext, level2

#124 Framer Motion Animation added to Licensing Page
  src/main.jsx
  src/pages/LicensingPage.jsx
  src/pages/PrivacyPolicy.jsx
Labels: enhancement, gssoc-ext, level3

#126 Created professional afilated page
  src/pages/AffiliateProgram.jsx
Labels: gssoc-ext, level3

#127 Animations added & UI standardized
  src/pages/TermsAndCondition.jsx
Labels: enhancement, gssoc-ext, level3

#138 env.md file created
  .env.sample
  env.md
  package-lock.json
  src/pages/AllPost.jsx
Labels: gssoc-ext, level3

#139 individual post page layout enhanced
  src/pages/Post.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#144 Added a fully functional profile page for blogger
  src/componenets/Header/Header.jsx
  src/componenets/ProfilePage.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level3

#145 enhancing all posts page
  src/componenets/PostCard.jsx
  src/pages/AllPost.jsx
Labels: enhancement, gssoc-ext, level3

#153 addition of social media links
  src/componenets/Footer/Footer.jsx
Labels: enhancement, gssoc-ext, level3

#157 Login/Signup with Password Recovery
  src/componenets/ForgotPasswordModal.jsx
  src/componenets/Login.jsx
  src/componenets/Signup.jsx
Labels: enhancement, gssoc-ext, level3

#171 Changed header
  package-lock.json
  package.json
  src/App.css
  src/componenets/Header/Header.jsx
  src/componenets/Header/LogoutBtn.jsx
  src/components/ui/button.tsx
  src/components/ui/navigation-menu.tsx
Labels: gssoc-ext, level3

#177 Share with friends section updated
  src/pages/Post.jsx
Labels: enhancement, gssoc-ext, level3

#183 Responsive all post page issue #142
  package-lock.json
  package.json
  src/componenets/PostCard.jsx
  src/pages/AllPost.jsx
Labels: enhancement, gssoc-ext, level3

#186 Support Page updated
  src/componenets/SupportPage.jsx
Labels: enhancement, gssoc-ext, level3

#193 Linked buttons get-started and learn-more
  src/componenets/Hero/Hero.jsx
Labels: enhancement, level3

#111 Help Page completed
  package-lock.json
  package.json
  src/componenets/Footer/Footer.jsx
  src/components/ui/accordion.tsx
  src/main.jsx
  src/pages/HelpPage.jsx
  tailwind.config.js
Labels: enhancement, gssoc-ext, level3

#198 Added chatbot
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/componenets/Chatbot.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level3

#200 Framer motion animation added to FAQ Page
  src/pages/FAQ.jsx
Labels: enhancement, gssoc-ext, level3

#218 display the content of post
  src/componenets/PostCard.jsx
  src/pages/Post.jsx
Labels: enhancement

#203 Errors Fixed: 1
  src/App.jsx
  src/componenets/Footer/Footer.jsx
  src/componenets/PostCard.jsx
  src/main.jsx
  src/pages/ContactPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SupportPage.jsx
Labels: enhancement, gssoc-ext, level3

#219 some necessary changes
  src/main.jsx
Labels: enhancement, gssoc-ext, level3

#221 some necessary changes
  src/App.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level3

#207 changed components of Add Post: 6
  package-lock.json
  package.json
  src/App.jsx
  src/componenets/postForm/PostForm.jsx
  src/components/ui/dialog.tsx
  src/components/ui/label.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level3

#220 Change language using google translator
  src/componenets/Footer/Footer.jsx
  src/componenets/GoogleTranslator.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level3

#175 Categorical display of Posts : 3
  package-lock.json
  package.json
  src/appwrite/configAppwrite.js
  src/componenets/postForm/PostForm.jsx
  src/components/ui/command.tsx
  src/components/ui/popover.tsx
  src/pages/AllPost.jsx
Labels: enhancement, gssoc-ext, level3

#229 Add New Press Kit Page with Centered Titles and Hover Transitions
  package-lock.json
  package.json
  src/App.jsx
  src/componenets/Footer/Footer.jsx
  src/main.jsx
  src/pages/Presskit.css
  src/pages/Presskit.jsx
Labels: enhancement, gssoc-ext, level3

#238 Landing Page renewed
  src/componenets/Hero/Hero.jsx
  src/main.jsx
Labels: gssoc-ext, level3

#239 login page created
  src/App.jsx
  src/main.jsx
  src/pages/SignIn.jsx
Labels: enhancement, gssoc-ext, level3

#245 addition of social media links and footer enhancement
  src/componenets/Footer/Footer.jsx
Labels: enhancement, gssoc-ext, level3

#248 Added Error404 page
  src/main.jsx
  src/pages/Error404.jsx
Labels: enhancement, gssoc-ext, level3

#251 Feature : Added Back-to-home button to SignIn and SignUp pages.
  package-lock.json
  src/pages/SignIn.jsx
  src/pages/SignUpp.jsx
Labels: enhancement, gssoc-ext, level2

#240 enhanced all post page
  package-lock.json
  package.json
  src/componenets/PostCard.jsx
  src/components/ui/carousel.tsx
  src/pages/AllPost.jsx
Labels: gssoc-ext, level3

#265 fetched blogs written by current user
  src/appwrite/configAppwrite.js
  src/componenets/postForm/PostForm.jsx
  src/pages/ProfilePage.jsx
Labels: enhancement, gssoc-ext, level3

#267 bug corrected
  src/appwrite/configAppwrite.js
  src/componenets/postForm/PostForm.jsx
Labels: enhancement, gssoc-ext, level3

#269 draft posts fetched
  src/appwrite/configAppwrite.js
  src/pages/ProfilePage.jsx
Labels: enhancement, gssoc-ext, level3

#271 delete post fixed
  package.json
  src/components/ui/button.tsx
  src/pages/Post.jsx
Labels: enhancement, gssoc-ext, level3

#277 added features page
  src/componenets/Footer/Footer.jsx
  src/main.jsx
  src/pages/Features.jsx
Labels: enhancement, gssoc-ext, level3

#291 [fix]: changing the browser logo
  package-lock.json
  src/assets/favicon.png
Labels: enhancement, gssoc-ext, level2

#286 FIX: Contact Us form Full Name validation
  src/pages/ContactPage.jsx
Labels: gssoc-ext, level2

#287 FIX : Contact Us form Phone validation
  src/pages/ContactPage.jsx
Labels: enhancement, gssoc-ext, level2

#293 [fix]: Documentation changes in readme.md
  README.md
Labels: enhancement, gssoc-ext, level1

#299 Added Feedback Form
  src/componenets/Footer/Footer.jsx
  src/main.jsx
  src/pages/Feedback.css
  src/pages/Feedback.jsx
Labels: enhancement, gssoc-ext, level3

#303 Automated project structure updation using github workflows, python script and action bot
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: enhancement, gssoc-ext, level3

#304 Oauth added[Google , Facebook, LinkedIn, Github]
  package-lock.json
  package.json
  src/pages/SignIn.jsx
  src/pages/SignUpp.jsx
Labels: enhancement, gssoc-ext, level3

#308 🛠️FIX: Sign up form Full Name validation
  src/pages/SignUpp.jsx
Labels: enhancement, gssoc-ext, level1

#326 image upload functionality
  PROJECT_STRUCTURE.md
  package-lock.json
  package.json
  repo_structure.txt
  src/App.jsx
  src/appwrite/auth.js
  src/appwrite/configAppwrite.js
  src/componenets/Signup.jsx
  src/componenets/postForm/PostForm.jsx
  src/pages/ProfilePage.jsx
Labels: enhancement, gssoc-ext, level3

#334 Hover effect corrected
  package-lock.json
  src/App.css
  src/componenets/Header/Header.jsx
Labels: enhancement, gssoc-ext, level3

#336 Added Category, Tags and metadata to the database
  src/appwrite/configAppwrite.js
  src/componenets/postForm/PostForm.jsx
Labels: enhancement, gssoc-ext, level3

#331 issue where users cannot properly update their profile details (e.g., name, bio).
  src/appwrite/auth.js
  src/componenets/Signup.jsx
  src/pages/ProfilePage.jsx
Labels: enhancement, gssoc-ext, level2

#339 Integrated AI Chatbot
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/api/chatbot.js
  src/components/ui/Chatbot.jsx
Labels: enhancement, gssoc-ext, level3

#353 Offline First Experience with Caching and Sync Status Indicator
  .gitignore
  package-lock.json
  package.json
  public/offline.html
  public/service-worker.js
  src/main.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3
