Repository anuj123upadhyay/MegaBlog, pull requests merged in 2024-11, with the labels that each got.

#356 Updated the readme file
  README.md
  assets/GSSoC-Ext.png
  assets/hacktoberfest.png
  assets/image
Labels: documentation, gssoc-ext, level1

#368 Profile page responsive
  PROJECT_STRUCTURE.md
  repo_structure.txt
  src/pages/ProfilePage.jsx
Labels: enhancement, gssoc-ext, level2

#369 Add Chatbot Icon Near Back-to-Top Button & Replace Chat Button with Icon
  src/App.css
  src/componenets/Chatbot.jsx
  src/components/ui/BackToTopButton.tsx
Labels: enhancement, gssoc-ext, level2

#372 Replace 'Back to Home' Button with Home Icon on Login and Sign-Up Pages
  package-lock.json
  src/pages/SignIn.jsx
  src/pages/SignUpp.jsx
Labels: enhancement, gssoc-ext, level2

#376 Website Theme Changing on Mode Switch
  index.html
  src/App.css
  src/componenets/Footer/Footer.jsx
  src/componenets/Header/Header.jsx
  src/componenets/Hero/Hero.jsx
  src/index.css
Labels: enhancement, gssoc-ext, level2

#379 Revamped Profile Page
  package-lock.json
  package.json
  src/pages/ProfilePage.jsx
Labels: enhancement, gssoc-ext, level3

#391 Added ai supported chatbot
  package-lock.json
  package.json
  src/App.jsx
  src/componenets/AiChatbot.jsx
  src/componenets/Chatbot.jsx
  src/componenets/Footer/Footer.jsx
Labels: enhancement, gssoc-ext, level3

#393 Implemented backend for contact form with validation, saving data to MongoDB, and handling errors for smooth user experience
  server/app.js
  server/controller/contactController.js
  server/models/contact.js
  server/routes/contactRoute.js
  src/main.jsx
  src/pages/ContactPage.jsx
Labels: enhancement, gssoc-ext, level3

#394 Added frontend and backend for feedback details
  server/app.js
  server/controller/feedbackController.js
  server/models/feedback.js
  server/routes/feedbackRoute.js
  src/componenets/Header/Header.jsx
  src/pages/Feedback.jsx
Labels: enhancement, gssoc-ext, level3

#407 Interactive Discussion Forum with CURD operation & Responsive Design
  src/componenets/Footer/Footer.jsx
  src/componenets/Header/Header.jsx
  src/main.jsx
  src/pages/DiscussionForum.jsx
Labels: enhancement, gssoc-ext, level3

#404 Added auto scroable beautiful testimonial
  src/componenets/Hero/Hero.jsx
  src/componenets/Testimonial.jsx
Labels: gssoc-ext, level3

#409 Added AI generated Trending title
  server/generateFromAi.py
  src/componenets/Hero/Hero.jsx
  src/componenets/TrendingTitle.jsx
Labels: enhancement, gssoc-ext, level3

#410 Added mail feature on contact us form for instant reply
  server/controller/contactController.js
  server/sendContactDetailsToAdmin.js
Labels: enhancement, gssoc-ext, level3

#411 Added terms of use page
  src/componenets/Footer/Footer.jsx
  src/componenets/TermsOfUse.jsx
  src/main.jsx
Labels: gssoc-ext, level2

#412 Fixes navbar issue on scrolling
  src/componenets/Header/Header.jsx
Labels: enhancement, gssoc-ext, level2

#413 Added contributor page where we show our contributor and open issues
  src/componenets/Contributor.jsx
  src/componenets/Footer/Footer.jsx
  src/componenets/Header/Header.jsx
  src/main.jsx
Labels: enhancement, gssoc-ext, level2

#417 Updated Footer.jsx @1
  src/componenets/Footer/Footer.jsx
Labels: gssoc-ext, level2

#418 changes subscribe from footer to subscribe section @2
  server/app.js
  server/controller/newsletterController.js
  src/componenets/Footer/Footer.jsx
  src/componenets/Hero/Hero.jsx
Labels: gssoc-ext, level3

#422 about Page @4
  src/componenets/Hero/Hero.jsx
  src/main.jsx
  src/pages/About.jsx
Labels: enhancement, gssoc-ext, level3

#427 Displayed metadata , tags on all posts page and added styling to diff… @7
  src/componenets/PostCard.jsx
  src/components/ui/carousel.tsx
  src/pages/AllPost.jsx
Labels: enhancement, gssoc-ext, level3

#430 Add Story Page for Blogger Platform
  src/main.jsx
  src/pages/Stories.jsx
Labels: gssoc-ext, level3

#431 Build Backend for Stories Page: Implement POST and GET Routes ✨🚀
  server/app.js
  server/controller/postsController.js
  server/models/postModel.js
  server/routes/storiesRoutes.js
  src/componenets/Footer/Footer.jsx
  src/main.jsx
  src/pages/Stories.jsx
Labels: gssoc-ext, level3

#432 Removed link bugs
  server/package.json
  src/componenets/Footer/Footer.jsx
Labels: level3

#434 Footer alignment corrected
  src/componenets/Footer/Footer.jsx
Labels: bug, gssoc-ext, level2

#436 search Bar @9
  src/appwrite/configAppwrite.js
  src/componenets/SearchBar.jsx
  src/components/ui/badge.tsx
  src/pages/AllPost.jsx
Labels: gssoc-ext, level3

#437 edit post fornt and backend completed with skeleton
  src/componenets/EditPostForm.jsx
  src/main.jsx
  src/pages/EditPost.jsx
  src/pages/Post.jsx
Labels: enhancement, gssoc-ext, level3

#438 routing issue
  src/main.jsx
Labels: gssoc-ext, level3

#439 Update AllPost.jsx
  src/pages/AllPost.jsx
Labels: gssoc-ext, level3

#444 Delayed by 2 seconds
  src/componenets/PostCard.jsx
  src/pages/AllPost.jsx
Labels: gssoc-ext, level3
